# Generated by Django 6.0.2 on 2026-03-08 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
