# Generated by Django 6.0.2 on 2026-03-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
